parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sibudec
    database_user: sibudec
    database_password: sibudec
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 187d3aa984adc77bcd4a586d9857b892
    database_path: null
