sibudec_front:
    resource: "@SibudecFrontBundle/Controller/"
    type:     annotation
    prefix:   /

sibudec_admin:
    resource: "@SibudecAdminBundle/Controller/"
    type:     annotation
    prefix:   /
